name: Pumpkin Papers
favicon: null
layout_spectrum: 0.558570439228788
typography_spectrum: 0.9929782408289611
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.32520218612626195
  lightness: 0.5446760258637369
  saturation: 0.35391040588729084
  rhythmicContrast: 0.9144712258130312
purpose: []
